### ISSUE TITLE
Unable to generate Sequence Diagram - macOS 

### ISSUE THREAD

**Issue by krish777** [judepayne/dictim#9] opened 2024-08-25 02:37 UTC
Step 1: Create a [d2](https://github.com/user-attachments/files/16738634/seq.d2.txt) file

Step 2: Create a [dictim file](https://github.com/user-attachments/files/16738645/seq.edn.txt) which contains style. 

Step 3: Run the dictim command to generate the d2 file.

Step 4: System generates the [generatedD2File.txt](https://github.com/user-attachments/files/16738659/generatedD2File.txt) file **without any issues.** 

But [expected d2 file](https://github.com/user-attachments/files/16738715/expectedD2File.txt) is attached. Please check it out.

Step 5: Open the above generated d2 file. The **shape: sequence_diagram** is missing from line 1

Step 6: Convert the generated D2 file from step 4 to png. 
<img width="332" alt="layer-actual" src="https://github.com/user-attachments/assets/f0432251-92d3-47fd-9d66-07b6171e0a3d">

But **expected diagram** is the one like the below one
<img width="454" alt="sequcence-expected" src="https://github.com/user-attachments/assets/2640b498-3bc7-44d6-a70b-e777ace245d0">

**Comment by judepayne** [comment] 2024-08-27 11:08
Hi, Pretty sure this is the same issue is #5, which is now fixed (but unreleased). Please read through and check that you can agree. You can pull the latest (unrealised) sha and test for yourself in the repl (rather than the command line since this is unreleased).
In the old pre-fix code, the sequence_diagram attribute was getting removed post parse and just before the application of the template. In the new version, that is no longer the default behaviour.
I do this this is worth testing though just because sequence_diagram is a top level attribute and though I'm confident it is no longer being removed, not 100% sure that when top level attributes ('directives') are faithfully merged. Worth a test. If still an issue, I will fix

**Comment by judepayne** [comment] 2024-08-27 11:10
The relevant code is here https://github.com/judepayne/dictim/blob/main/src/cmd/dictim.clj lines 355-359

**Comment by judepayne** [comment] 2024-08-28 18:27
I've confirmed that this is fixed by the fix to #5 - it's the same issue, so closing this

**Closed as completed by judepayne** 2024-08-28 18:27 UTC
